/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-07-10 03:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import guest.control.GuestBean;

public final class guest_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>방명록</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h3>방명록</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<a  href=\"guest?action=input\">방명록쓰기</a>\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t");
 ArrayList<GuestBean> list = (ArrayList<GuestBean>)request.getAttribute("list"); 
      out.write("\r\n");
      out.write("\t\t\t<tr bgcolor=\"skyblue\">\r\n");
      out.write("\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t<th>내용</th>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
for(int i=0;i< list.size();i++){ 
				int id = list.get(i).getId();
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( id);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( list.get(i).getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( list.get(i).getTel());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( list.get(i).getGdate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"guest?action=update&id=");
      out.print( id);
      out.write('"');
      out.write('>');
      out.print( list.get(i).getContents());
      out.write("</a></td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</table><br>\r\n");
      out.write("\t\t");

     		 int p = Integer.parseInt(request.getParameter("page"));//2페이지 가정      
 		
      out.write(" \r\n");
      out.write("\t\t");
if(p==1){//첫페이지 였을때 
      out.write("\r\n");
      out.write(" \t\t 이전  \r\n");
      out.write("  \t\t");
}else{ 
      out.write("\r\n");
      out.write("  \t\t<a href=\"guest?page=");
      out.print( p-1 );
      out.write("\">이전</a>   \r\n");
      out.write("  \t\t");
} 
      out.write("\r\n");
      out.write("  \t\t");

  			int total = Integer.parseInt(request.getAttribute("total").toString());
  		
      out.write("\r\n");
      out.write("  \t\t");
if(p==total/10){ 
      out.write("\r\n");
      out.write("  \t\t다음\r\n");
      out.write("  \t\t");
}else{ 
      out.write("\r\n");
      out.write("  \t\t<a href=\"guest?action=list&page=");
      out.print( p+1 );
      out.write("\">다음</a>\r\n");
      out.write("  \t\t");
} 
      out.write("\r\n");
      out.write("  \t\t<br><br>\r\n");
      out.write("  \t\t<input type=\"button\" name=\"first\" value=\"첫페이지\" onclick=\"javascript:location.href='guest?action=list&page=1'\">\r\n");
      out.write("  \t\t");

  			for (int i=1; i<=total; i++){
  				out.print("[<a href='guest?action=list&page="+i+"'>"+i+"</a>]");
  			}
  		
      out.write("\r\n");
      out.write("  \t\t<input type=\"button\" name=\"last\" value=\"마지막페이지\" onclick=\"javascript:location.href='guest?action=list&page=");
      out.print( total);
      out.write("'\">\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
